//
// Created by andre on 10/13/2021.
//

#ifndef SIMPLESTUDENTRECORDSYSTEM_DOUBLENODE_H
#define SIMPLESTUDENTRECORDSYSTEM_DOUBLENODE_H


class DoubleNode {

};


#endif //SIMPLESTUDENTRECORDSYSTEM_DOUBLENODE_H
