//
// Created by andre on 10/12/2021.
//
#include "SingleNode.h"

#ifndef SIMPLESTUDENTRECORDSYSTEM_SINGLELINKEDLIST_H
#define SIMPLESTUDENTRECORDSYSTEM_SINGLELINKEDLIST_H


class SingleLinkedList {

};


#endif //SIMPLESTUDENTRECORDSYSTEM_SINGLELINKEDLIST_H
